### ISSUE TITLE
Proxy does not filter on collection name

### ISSUE THREAD

**Issue by st3fan** [mozilla/esFrontLine#4]
This might not be an issue if the only index in ES is the bugzilla one. But right now it is possible to query any available index.

For example:

```
curl -v -XGET -d '{"query": { "term": { "email": "sarentz@mozilla.com" } }}' \
    "http://127.0.0.1:9292/org_chart131113_105007/_search"
```

I think it is best to add a list of allowed indexes to the `settings.json` so that the proxy can deny requests for anything not whitelisted.

**Comment by st3fan** [comment]
Maybe there are also system indexes that we do not want to expose?

**Comment by klahnakoski** [comment]
I am not aware ES has any system indexes.  But this is part of the bigger issue of unknown unknowns.  I will add some more logging to this program with the hope we can record successful attack vectors.

It was deliberate to not filter by index because we want add other public indexes in the future.  The whole cluster is dedicated to public data that can be recovered from other sources should it be damaged.

**Comment by st3fan** [comment]
I am fine with not having a whitelist if there is a guarantee that the ES cluster only contains public data.

**Comment by st3fan** [comment]
Adding logging is a good idea, but I don't think 'lets wait for attack vectors' is a good idea. Instead I think it would be better if this project had some unit tests to which we can add a bunch of attacks so that we can proof that bad requests are correctly blocked. Do you think that is possible?

**Comment by klahnakoski** [comment]
I would imagine an attack test suite would be a lot more work, unless there is a library that does that type of thing already.  Since this is public and replaceable data, I do not believe this extra effort is justified at this time.   The effort put into protecting this data should be proportional to the expected losses.  The expected loss is 5min of human time to re-start the ETL and fix any damage.

**Comment by st3fan** [comment]
I think 'attack test suite' sounds more complicated than it really is. I'm really just thinking of some unit tests that confirm that for example the logic in the `filter` function is correct. In Python this is a single unit test class with a bunch of 2 line tests.

It is good if it is easy to rebuild the database, but I don't think it will be monitored 24/7 so if it were for example possible to make modifications to this data through some bug and some other tool depends on that data, then that could be a security risk.

**Comment by klahnakoski** [comment]
A whitelist was added long ago.  Here is a test to verify: https://github.com/mozilla/esFrontLine/commit/65012249a7fe6562277f15d09816edbe02609fed
